/*
 *  Robo Maze Blast
 *  Copyright (C) 2008-2013 Christian Lins <christian@lins.me>
 *  Copyright (C) 2008 Kai Ritterbusch <kai.ritterbusch@googlemail.com>
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package games.homeship.robomazeblast.client.gui;

import games.homeship.robomazeblast.Main;
import java.awt.Color;
import java.awt.Font;
import java.awt.Insets;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.border.LineBorder;

/**
 * Shows the LoginPanel when application is started.
 *
 * @author Kai Ritterbusch
 * @author Christian Lins
 */
@SuppressWarnings("serial")
public class MenuPanel extends javax.swing.JPanel {

    private static volatile MenuPanel instance = null;

    public static MenuPanel getInstance() {
        return instance;
    }

    private final JButton[] menuButtons;

    public MenuPanel() {
        instance = this;
        initComponents();
        menuButtons = new JButton[]
            {btnNewGame, btnContinueGame, btnSettings, btnLeaveGame};

        setBackground(ElementPainter.BACKGROUND_COLOR);

        for (var btn : menuButtons) {
            unswingButton(btn);
        }
    }

    private void setPixelFont(JComponent comp) {
        comp.setFont(new Font("Silkscreen", Font.PLAIN, 24));
        comp.setForeground(Color.WHITE);
    }

    private void unswingButton(JButton button) {
        setPixelFont(button);
        button.setContentAreaFilled(false);
        button.setBorderPainted(button.isSelected());
        button.setBorder(new LineBorder(Color.WHITE));
        button.setFocusPainted(false);
        button.setMargin(new Insets(10, 15, 10, 15));
    }

    public void keyPressed(KeyEvent evt) {
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_ENTER -> {
                if (btnNewGame.isSelected()) {
                    btnNewGameActionPerformed(null);
                } else if(btnLeaveGame.isSelected()) {
                    btnLeaveGameActionPerformed(null);
                }
            }
            case KeyEvent.VK_DOWN -> {
                if (btnNewGame.isSelected()) {
                    selectButton(btnContinueGame);
                } else if(btnContinueGame.isSelected()) {
                    selectButton(btnSettings);
                } else if(btnSettings.isSelected()) {
                    selectButton(btnLeaveGame);
                } else if(btnLeaveGame.isSelected()) {
                    selectButton(btnNewGame);
                }
            }
            case KeyEvent.VK_UP -> {
                if (btnNewGame.isSelected()) {
                    selectButton(btnLeaveGame);
                } else if(btnContinueGame.isSelected()) {
                    selectButton(btnNewGame);
                } else if(btnSettings.isSelected()) {
                    selectButton(btnContinueGame);
                } else if(btnLeaveGame.isSelected()) {
                    selectButton(btnSettings);
                }
            }
        }
    }

    private void selectButton(JButton btn) {
        for (var otherBtn : menuButtons) {
            otherBtn.setSelected(false);
            otherBtn.setBorderPainted(false);
        }

        btn.setSelected(true);
        btn.setBorderPainted(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNewGame = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        btnContinueGame = new javax.swing.JButton();
        btnSettings = new javax.swing.JButton();
        btnLeaveGame = new javax.swing.JButton();

        btnNewGame.setText("New Game");
        btnNewGame.setToolTipText("");
        btnNewGame.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNewGame.setMargin(new java.awt.Insets(5, 14, 5, 14));
        btnNewGame.setNextFocusableComponent(btnContinueGame);
        btnNewGame.setSelected(true);
        btnNewGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMouseEntered(evt);
            }
        });
        btnNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewGameActionPerformed(evt);
            }
        });

        btnContinueGame.setText("Continue Game");
        btnContinueGame.setMargin(new java.awt.Insets(5, 14, 5, 14));
        btnContinueGame.setNextFocusableComponent(btnSettings);
        btnContinueGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMouseEntered(evt);
            }
        });

        btnSettings.setText("Settings");
        btnSettings.setMargin(new java.awt.Insets(5, 14, 5, 14));
        btnSettings.setNextFocusableComponent(btnLeaveGame);
        btnSettings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMouseEntered(evt);
            }
        });

        btnLeaveGame.setText("Leave Game");
        btnLeaveGame.setMargin(new java.awt.Insets(5, 14, 5, 14));
        btnLeaveGame.setNextFocusableComponent(btnNewGame);
        btnLeaveGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMouseEntered(evt);
            }
        });
        btnLeaveGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeaveGameActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(filler1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(btnContinueGame, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                    .add(btnNewGame, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(btnSettings, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(btnLeaveGame, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(btnNewGame))
                    .add(layout.createSequentialGroup()
                        .add(20, 20, 20)
                        .add(filler1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btnContinueGame)
                .add(18, 18, 18)
                .add(btnSettings)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btnLeaveGame)
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewGameActionPerformed
        try {
            System.out.println("Start new game");
            Main.startSingleGame();
        } catch (IOException ex) {
            Logger.getLogger(MenuPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnNewGameActionPerformed

    private void btnLeaveGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeaveGameActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnLeaveGameActionPerformed

    private void btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMouseEntered
        if (evt.getSource() instanceof JButton) {
            selectButton((JButton)evt.getSource());
        }
    }//GEN-LAST:event_btnMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinueGame;
    private javax.swing.JButton btnLeaveGame;
    private javax.swing.JButton btnNewGame;
    private javax.swing.JButton btnSettings;
    private javax.swing.Box.Filler filler1;
    // End of variables declaration//GEN-END:variables

}
